### ISSUE TITLE
Review Kanban Board

### ISSUE THREAD

**Issue by Gopxfs** [Draxeytina/Back-end_Tesla-Booking#20]
[Link to Kanban Board](https://github.com/users/Draxeytina/projects/4/views/1)
# Review of kanban board - Final Capstone
[Back-end](https://github.com/Draxeytina/Back-end_Tesla-Booking)
[Front-end](https://github.com/Draxeytina/Front-end_Tesla-Booking)
## We are a team of 5 members:
- @fibini
- @franclobo 
- @Gopxfs 
- @Draxeytina
- @waqaskanju 

## Kanban board screenshot:
![image](https://user-images.githubusercontent.com/42799579/196807680-4828e314-9168-45b8-81d2-aa554a273a4c.png)

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However, there are some issues preventing me from giving the 👍 


- I am not seeing the link to the kanban board, I do see issues that are great, but I do not see a project board in either of the repos linked. (One board is fine)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by waqaskanju** [comment]
done.
![image](https://user-images.githubusercontent.com/13853450/196817147-b0cb0b84-db7f-4dfc-8513-6f1e0b808477.png)

**Comment by mcrd25** [comment]
Sorry, don't know how I missed that, apologies - This is what I see: 
![image](https://user-images.githubusercontent.com/31193823/196818741-6f486cac-719e-4d8c-9c0e-f122715277b6.png)

Have not submitted review yet, but that's what I see

**Comment by Gopxfs** [comment]
> Sorry, don't know how I missed that, apologies - This is what I see: ![image](https://user-images.githubusercontent.com/31193823/196818741-6f486cac-719e-4d8c-9c0e-f122715277b6.png)
> 
> Have not submitted review yet, but that's what I see

Hello @mcrd25 , can you check it again? We made it private, sorry for the inconvenient 😅

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by Gopxfs** [comment]
> Hi Team,
> 
> In my opinion, you are ready to move on to the next step! ⏭️
> 
> Good luck! 🎉
> 
> Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

Thanks for your patience!
